#!/usr/pkg/bin/perl

use warnings;
use strict;

package printlabels;

sub read_file_into_one_big_string {
	my ($filename) = @_;
	local $/ = undef;
	open FILE, $filename or die "Couldn't open file: $!";
	binmode FILE;
	my $contents = <FILE>;
	close FILE;
	return $contents;
}

sub one_address_per_line {
	my ($as_one_big_string) = @_;
	return sort split("\n", $as_one_big_string);
}

sub one_address_per_line_from_file {
	my ($filename) = @_;
	my $contents = read_file_into_one_big_string($filename);
	return one_address_per_line($contents);
}

sub extract_address_parts {
	my ($input_address) = @_;
	chomp($input_address);
	return split(/,/, $input_address);
}

sub format_address {
	my ($last, $first, $title, $street) = @_;
	return <<EOT;
$title $first $last
$street
EOT
}

sub do_all {
	my (@input_addresses) = @_;
	return join(
		"\n",
		map { printlabels::format_address(
			printlabels::extract_address_parts($_)
		) } @input_addresses,
	);
}

sub main {
	my ($filename) = @_;
	defined $filename
		&& print do_all(one_address_per_line_from_file($filename));
}

main(@ARGV) unless caller();

1
